### ISSUE TITLE
Use a lexicographic Labels order when constructing a `TensorBlock` and a `TensorMap`

### ISSUE THREAD

**Issue by PicoCentauri** [metatensor/metatensor#142]
When doing operations on equistore objects, like a `TensorBlock` or `TensorMap` we perform checks to verify that the shapes are valid for the requested operation. Especially when comparing two instances it is important that the order of the values is the same. Swapped labels of otherwise identical instances could make it hard to debug the code for users.

Therefore I suggest that we introduce a Lexicographic order of Labels when constructing a `TensorBlock` and a `TensorMap`. Since this is something that affects the core of the whole library it should be done on the lowest Rust/C level.

**Comment by Luthaf** [comment]
Here is some consensus we reached during the last meeting about this:

1: if Labels are not lexicographically sorted, the TensorBlock are using a [COO](https://en.wikipedia.org/wiki/Sparse_matrix#Coordinate_list_(COO)) (coordinate) sparse data format; while if they are sorted, we are using a special case of this COO format that is closer to [CSR](https://en.wikipedia.org/wiki/Sparse_matrix#Compressed_sparse_row_(CSR,_CRS_or_Yale_format)) (compressed sparse row storage). Both can be useful and interesting, and we need to think more about it to understand what we need

2. We could either always force the Labels to be sorted, or have a boolean flag on them indicating if they are sorted. If they are, we could use special algorithms for faster implementation of operations

**Comment by Luthaf** [comment]
> I have a more general question about sorting: Shouldn't on the creation of the TensorBlock the Labels (name and entries) _always_ be sorted (at least by default) and the values accordingly to it reordered? At the moment the label entries have to be identically ordered to do operations like `add`. To cover in the metadata equality check `_check_blocks` arbitrary orders of the label entries (and names) is to put them in some canonical order like sorted. It is a bit opaque to the user at first, but with docs it should be clear. I don't see any other way to deal with the permutation problem of Labels and it seems to me that equistore should be able to handle this.

> @agoscinski  in https://github.com/lab-cosmo/equistore/issues/278#issuecomment-1587290648

Moving the discussion here, since your message seems to be about the same issue.

I don't think we should always sort everything on TensorBlock creation, for a couple of reasons:

- there is not always a sorting order that's obviously better than the alternatives (we can always do lexicographic sorting, but it might not give any advantage compared to another sorting). For example, this would be the case when handling more than one center in the representation (we could sort `i` first or `j` first, and both would be similarly valid)
- I had a chat recently with @andreagrisafi who was telling me he is using a different order than the default one to better integrate in his workflow, so it seems that there are use cases in keeping things out of lexicographic order.


> I don't see any other way to deal with the permutation problem 

I would suggest adding a `Labels.is_permutation_of(self, other: Labels)` function that would also return the permutation to transform `self` into `other` on success. This can then be used to implement all sort of fancy operations, and handle the operations with permutation invariance.

**Comment by agoscinski** [comment]
Okay to be more clear the main reason I advocate for some canonical order is just that we can do operations faster. Reordering the arrays for each operation (like `add`) will cost some significant time. I can see that we don't want to enforce a canonical order, because there is always a use case where you rather want the flexibility, but I think we should not ignore this issue.

When we start to allow permutations in the TensorMaps for operations as `add` and compute the transformation, I would beforehand check if the TensorMaps have the same order (should be O(N)) to see if the remapping is really necessary. I think that is good enough for me to cover my efficiency concerns. What do you think?

And maybe at some point later, one could think about a `is_canonical_ordered` tag on TensorMap/TensorBlock that when true ensures that the TensorMap is in some specific order so we can even skip the check that verifies that. But I don't think that the check will have efficiency issues in a relevant in near future.

**Comment by Luthaf** [comment]
I'm fine with doing an `O(n)` check for now, and move it to a flag on the Labels in equistore-core later!

**Comment by Luthaf** [comment]
We now have the `sort` operation to help with the initial concern for this issue. I don't think we will ever require things to be sorted, so if there is a speed reason to have a `is_lexicographic_ordered` tag on Labels or any other class we can play with this in a separate issue.
