### ISSUE TITLE
Better error message when trying to assign to block.values directly

### ISSUE THREAD

**Issue by PicoCentauri** [metatensor/metatensor#40]
It could be useful to manipulate the descriptor values of a block after they have been calculated. However, expressions like 

```python
block.values *= -1
```

are not allowed an lead to `AttributeError: can't set attribute`. There is a workaround like 

```python
for r in block.values:
    r *= -1
```

which works fine, but in my view the first option should also work.

**Comment by ceriottm** [comment]
I think this i

**Comment by Luthaf** [comment]
This is a bit of a different issue from what we discussed @ceriottm. The previous issue was that the array itself was marked as read-only, which was fixed in 34446a7593cf44ff6f46d437accc1b4a2c9d1a53. This is an issue because there is no setter associated with the `values` property.

Basically, 

```py
block.values *= -1
```

expands to 

```py
block.values = block.values * -1
```

which expands to something like (since values is a property)

```py
block.set_values(block.values() * -1)
```

but there is no `block.set_values()`. This is the difference between changing the data inside the array, and allocating a new array altogether. We could add a setter for the values, but this would require adding a new function to the C API.

---

For the initial issue, something like this should work fine, without requiring allocating a new array:

```
block.values[:] *= -1
```

**Comment by ceriottm** [comment]
I see now. Yes, I think we should only allow operations in place. M might be nice to give a more helpful error message.

**Comment by Luthaf** [comment]
This will need to be solved in both the pure Python version of `TensorBlock` and in the TorchScript backend.

Steps to solve this:

- in the Python version of `metatensor-core`, we could add a `@values.setter` function to `TensorBlock` which would still raise an error, but point people to use `block.values[:] = ...` instead.
- in the TorchScript backend, we could do the same, but the setter would have to be defined in C++, and registered with the classe


After either of the above steps:
- add a test that tries to set values on a block and check that the expected error message is given

**Comment by DavideTisi** [comment]
I'll work on that
