### ISSUE TITLE
Inconsistent types for class metatensor.torch.atomistic.System

### ISSUE THREAD

**Issue by E-Rum** [metatensor/metatensor#714]
Can we somehow resolve the inconsistency of storing different types of properties in the metatensor.torch.atomistic.System format? What bugs me is why we keep standard properties (types, positions, cells) as torch.Tensors, while any additional properties (that are added via System.add_data()) are stored in a TensorBlock format?

**Comment by Luthaf** [comment]
So in the initial version of this class everything was stored using TensorBlock, but this was a bit clunky for simple things like positions/cell/types, so these where switched to torch::Tensor.

For arbitrary data stored in the system, I think we still need the option to store data in TensorBlock, since these could be complex data such as particle orientation as quaternions, or per-atom spherical tensors.

We could add the ability to store data as either TensorBlock or torch::Tensor in the systems, but that would be a bit more complex and force the user to use `system.get_data("name")` or `system.get_tensor_data("name")` since TorchScript does not like `Union[T, U]` in function outputs. 

What's your use case here? Storing charges in the system as TensorBlock is an issue?
