### ISSUE TITLE
`check_atomistic_model` raises warnings for extensions

### ISSUE THREAD

**Issue by frostedoyster** [metatensor/metatensor#796]
When checking an atomistic model that wants extensions, a warning is raised:
```
from metatensor.torch.atomistic import check_atomistic_model
check_atomistic_model("model-with-extensions.pt")
```
The warning:
```
[W1127 14:54:12.582821921 model.cpp:922] Warning: The model at 'model-with-extensions.pt' was exported with extension 'neighbors_convert' loaded (from 'pet/neighbors_convert.so'), but it does not seem to be currently loaded; proceed at your own risk. (function check_atomistic_model)
```

**Comment by Luthaf** [comment]
This is intentional, we check whether this model will likely be usable if loaded as-is down the line. You can use [`load_model_extensions`](https://docs.metatensor.org/latest/atomistic/reference/models/index.html#metatensor.torch.atomistic.load_model_extensions) before checking the model if you want to hide the warning.

What behavior did you expect?

**Comment by frostedoyster** [comment]
I don't know, ideally, given the function's name and signature, I would expect a valid model not to generate any errors or warnings

**Comment by Luthaf** [comment]
The point is that the model is not yet valid in the current environment, and one does need to load the extensions to make the model valid.

**Comment by frostedoyster** [comment]
Ok, I must be using it the wrong way
